# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ad964d9789321dfe0837efb96bd8274087a29e374f1f53fb587dabf98afa77f08bdc0c24045e3f88ba9a6a8aef39a51573e57bacf42bce56e31fd00fdc2c28

test:
  secret_key_base: a604bfa56aed11f8ffc3d34e71d2f52e29fc79af9c26886442bd6276839f3a843ca6a9deea2e61b78354d517becf354c29be447c9d1f9d260c25b75663b1b192

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
